# Generated by Django 3.2.5 on 2022-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220323_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=64, null=True, verbose_name='订单号'),
        ),
    ]
