# Generated by Django 3.2.5 on 2022-03-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_order_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='名称'),
        ),
    ]
